module BreedHelper
  DOG = [%w(Sem\ raça\ definida Sem\ raça\ definida),
         %w(Afegão\ Hound Afegão\ Hound),
         %w(Affenpinscher Affenpinscher),
         %w(Airedale\ Terrier Airedale\ Terrier),
         %w(Akita Akita),
         %w(American\ Staffordshire\ Terrier American\ Staffordshire\ Terrier),
         %w(Basenji Basenji),
         %w(Basset\ Hound Basset\ Hound),
         %w(Beagle Beagle),
         %w(Beagle\ Harrier Beagle\ Harrier),
         %w(Bearded\ Collie Bearded\ Collie),
         %w(Bedlington\ Terrier Bedlington\ Terrier),
         %w(Bichon\ Frisé Bichon\ Frisé),
         %w(Bloodhound Bloodhound),
         %w(Bobtail Bobtail),
         %w(Boiadeiro\ Australiano Boiadeiro\ Australiano),
         %w(Boiadeiro\ Bernês Boiadeiro\ Bernês),
         %w(Border\ Collie Border\ Collie),
         %w(Border\ Terrier Border\ Terrier),
         %w(Borzoi Borzoi),
         %w(Boston\ Terrier Boston\ Terrier),
         %w(Boxer Boxer),
         %w(Buldogue\ Francês Buldogue\ Francês),
         %w(Buldogue\ Inglês Buldogue\ Inglês),
         %w(Bull\ Terrier Bull\ Terrier),
         %w(Bulmastife Bulmastife),
         %w(Cairn\ Terrier Cairn\ Terrier),
         %w(Cane\ Corso Cane\ Corso),
         %w(Cão\ de\ Água\ Português Cão\ de\ Água\ Português),
         %w(Cão\ de\ Crista\ Chinês Cão\ de\ Crista\ Chinês),
         %w(Cavalier\ King\ Charles\ Spaniel Cavalier\ King\ Charles\ Spaniel),
         %w(Chesapeake\ Bay\ Retriever Chesapeake\ Bay\ Retriever),
         %w(Chihuahua Chihuahua),
         %w(Chow\ Chow Chow\ Chow),
         %w(Cocker\ Spaniel\ Americano Cocker\ Spaniel\ Americano),
         %w(Cocker\ Spaniel\ Inglês Cocker\ Spaniel\ Inglês),
         %w(Collie Collie),
         %w(Coton\ de\ Tuléar Coton\ de\ Tuléar),
         %w(Dachshund Dachshund),
         %w(Dálmata Dálmata),
         %w(Dandie\ Dinmont\ Terrier Dandie\ Dinmont\ Terrier),
         %w(Doberman Doberman),
         %w(Dogo\ Argentino Dogo\ Argentino),
         %w(Dogue\ Alemão Dogue\ Alemão),
         %w(Fila\ Brasileiro Fila\ Brasileiro),
         %w(Fox\ Terrier\ (Pelo\ Duro\ e\ Pelo\ Liso) Fox\ Terrier\ (Pelo\ Duro\ e\ Pelo\ Liso)),
         %w(Foxhound\ Inglês Foxhound\ Inglês),
         %w(Galgo\ Escocês Galgo\ Escocês),
         %w(Galgo\ Irlandês Galgo\ Irlandês),
         %w(Golden\ Retriever Golden\ Retriever),
         %w(Grande\ Boiadeiro\ Suiço Grande\ Boiadeiro\ Suiço),
         %w(Greyhound Greyhound),
         %w(Grifo\ da\ Bélgica Grifo\ da\ Bélgica),
         %w(Husky\ Siberiano Husky\ Siberiano),
         %w(Jack\ Russell\ Terrier Jack\ Russell\ Terrier),
         %w(King\ Charles King\ Charles),
         %w(Komondor Komondor),
         %w(Labradoodle Labradoodle),
         %w(Labrador\ Retriever Labrador\ Retriever),
         %w(Lakeland\ Terrier Lakeland\ Terrier),
         %w(Leonberger Leonberger),
         %w(Lhasa\ Apso Lhasa\ Apso),
         %w(Lulu\ da\ Pomerânia Lulu\ da\ Pomerânia),
         %w(Malamute do Alasca Malamute do Alasca),
         %w(Maltês Maltês),
         %w(Mastife Mastife),
         %w(Mastim\ Napolitano Mastim\ Napolitano),
         %w(Mastim\ Tibetano Mastim\ Tibetano),
         %w(Norfolk\ Terrier Norfolk\ Terrier),
         %w(Norwich\ Terrier Norwich\ Terrier),
         %w(Papillon Papillon),
         %w(Pastor\ Alemão Pastor\ Alemão),
         %w(Pastor\ Australiano Pastor\ Australiano),
         %w(Pinscher\ Miniatura Pinscher\ Miniatura),
         %w(Poodle Poodle),
         %w(Pug Pug),
         %w(Rottweiler Rottweiler),
         %w(Shih\ Tzu Shih\ Tzu),
         %w(Silky\ Terrier Silky\ Terrier),
         %w(Skye\ Terrier Skye\ Terrier),
         %w(Staffordshire\ Bull\ Terrier Staffordshire\ Bull\ Terrier),
         %w(Terra\ Nova Terra\ Nova),
         %w(Terrier\ Escocês Terrier\ Escocês),
         %w(Tosa Tosa),
         %w(Weimaraner Weimaraner),
         %w(Welsh\ Corgi\ (Cardigan) Welsh\ Corgi\ (Cardigan)),
         %w(Welsh\ Corgi\ (Pembroke) Welsh\ Corgi\ (Pembroke)),
         %w(West\ Highland\ White\ Terrier West\ Highland\ White\ Terrier),
         %w(Whippet Whippet),
         %w(Xoloitzcuintli Xoloitzcuintli),
         %w(Yorkshire\ Terrier Yorkshire\ Terrier)].freeze unless const_defined?('DOG')

  CAT = [%w(Sem\ raça\ definida Sem\ raça\ definida),
         %w(Abyssinian Abyssinian),
         %w(American\ Bobtail\ Longhair American\ Bobtail\ Longhair),
         %w(American\ Bobtail\ Shorthair American\ Bobtail\ Shorthair),
         %w(American\ Shorthair American\ Shorthair),
         %w(American\ Wirehair American\ Wirehair),
         %w(Arabian\ Mau Arabian\ Mau),
         %w(Asian\ Semi-long\ Hair Asian\ Semi-long\ Hair),
         %w(Australian\ Mist Australian\ Mist),
         %w(Bengal Bengal),
         %w(Bobtail\ Japonês Bobtail\ Japonês),
         %w(Bombaim Bombaim),
         %w(Brazilian\ Shorthair Brazilian\ Shorthair),
         %w(British\ Longhair British\ Longhair),
         %w(Burmês Burmês),
         %w(California\ Spangled\ Cat California\ Spangled\ Cat),
         %w(Chausie Chausie),
         %w(Cornish\ Rex Cornish\ Rex),
         %w(Curl\ Americano\ Pelo\ Curto Curl\ Americano\ Pelo\ Curto),
         %w(Curl\ Americano\ Pelo\ Longo Curl\ Americano\ Pelo\ Longo),
         %w(Cymric Cymric),
         %w(Devon\ Rex Devon\ Rex),
         %w(Domestic\ Long-Haired Domestic\ Long-Haired),
         %w(Domestic\ Short-Haired Domestic\ Short-Haired),
         %w(Don\ Sphynx Don\ Sphynx),
         %w(Egyptian\ Mau Egyptian\ Mau),
         %w(European European),
         %w(Exotic\ Shorthair Exotic\ Shorthair),
         %w(German\ Rex German\ Rex),
         %w(Havana Havana),
         %w(Himalaio Himalaio),
         %w(Khao\ Manee Khao\ Manee),
         %w(Korat Korat),
         %w(Kurilian\ Bobtail\ Longhair Kurilian\ Bobtail\ Longhair),
         %w(Kurilian\ Bobtail\ Shorthair Kurilian\ Bobtail\ Shorthair),
         %w(LaPerm\ Longhair LaPerm\ Longhair),
         %w(LaPerm\ Shorthair LaPerm\ Shorthair),
         %w(Maine\ Coon Maine\ Coon),
         %w(Manx Manx),
         %w(Mekong\ Bobtail Mekong\ Bobtail),
         %w(Munchkin\ Longhair Munchkin\ Longhair),
         %w(Munchkin\ Shorthair Munchkin\ Shorthair),
         %w(Nebelung Nebelung),
         %w(Norwegian\ Forest\ Cat Norwegian\ Forest\ Cat),
         %w(Ocicat Ocicat),
         %w(Ojos\ Azules\ Shorthair Ojos\ Azules\ Shorthair),
         %w(Oriental\ Longhair Oriental\ Longhair),
         %w(Oriental\ Shorthair Oriental\ Shorthair),
         %w(Persa Persa),
         %w(Peterbald Peterbald),
         %w(Pixiebob\ Longhair Pixiebob\ Longhair),
         %w(Pixiebob\ Shorthair Pixiebob\ Shorthair),
         %w(Ragamuffin Ragamuffin),
         %w(Ragdoll Ragdoll),
         %w(Russo\ Azul Russo\ Azul),
         %w(Sagrado\ da\ Birmânia Sagrado\ da\ Birmânia),
         %w(Savannah\ Cat Savannah\ Cat),
         %w(Scottish\ Fold Scottish\ Fold),
         %w(Selkirk\ Rex\ Longhair Selkirk\ Rex\ Longhair),
         %w(Selkirk\ Rex\ Shorthair Selkirk\ Rex\ Shorthair),
         %w(Serengeti Serengeti),
         %w(Siamês Siamês),
         %w(Siberian Siberian),
         %w(Singapura Singapura),
         %w(Snowshoe Snowshoe),
         %w(Sokoke Sokoke),
         %w(Somali Somali),
         %w(Sphynx Sphynx),
         %w(Thai Thai),
         %w(Tonkinese\ Shorthair Tonkinese\ Shorthair),
         %w(Toyger Toyger),
         %w(Turkish\ Angorá Turkish\ Angorá),
         %w(Turkish\ Van Turkish\ Van),
         %w(York\ Chocolate York\ Chocolate)].freeze unless const_defined?('CAT')
end
